runtime: python310
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  FLASK_ENV: "production"
  SECRET_KEY: "supersecretkey"
  SESSION_TYPE: "filesystem"

handlers:
  # Handle image files explicitly
  - url: /static/images/(.*\.(png|jpg|jpeg|gif))
    static_files: capstone_frontend_karim/static/images/\1
    upload: capstone_frontend_karim/static/images/.*\.(png|jpg|jpeg|gif)

  # Handle other static files
  - url: /static
    static_dir: capstone_frontend_karim/static

  # All remaining URLs are handled by the app
  - url: /.*
    script: auto
